const hobbies = [
  "Impressora 3D",
  "Radio Amador",
  "Atuação",
  "Artes Marciais",
  "Jogos de Tabuleiros",
  "Restauração de Livros",
  "Caligrafia",
  "Fazer Candelábros",
  "Programação Computacional",
  "Cozinhar",
  "Colorir",
  "Cosplay",
  "Escrita Criativa",
  "Croche",
  "Criptografia",
  "Dança",
  "Artes Digitais",
  "Teatro",
  "Desenho",
  "Do it yourself",
  "Electronicos",
  "Bordado",
  "Moda",
  "Arranjos de Flores",
  "Estudante de Línguas Estrangeiras",
  "Jogos Eletronicos",
  "RPG",
  "Apostas",
  "Genética",
  "Querbar Vidros",
  "Armeiro",
  "Cerveja Artesanal",
  "Patinação no Gelo",
  "Joalheiro",
  "Quebra Cabeças de Sobrevivencia",
  "Malabarismo",
  "Tricô",
  "Origami",
  "Fazer Facas/Espadas",
  "Trabalhos em Couro",
  "Lego",
  "Estudo de Cadeados",
  "Usinagem",
  "Metalurgia",
  "Magica",
  "Construção de Modelos",
  "Ouvir Música",
  "Pintar",
  "Tocar Instrumentos Músicais",
  "Animais de Estimação",
  "Cerâmica",
  "Quebra-Cabeças",
  "Estofador",
  "Ler",
  "Esculturas",
  "Costura",
  "Cantar",
  "Esportes",
  "Stand-up",
  "Sudoku",
  "Tênis de Mesa",
  "Taxidermia",
  "Video Game",
  "Ver Filmes",
  "Navegar Na Internet",
  "Escultura em Madeira",
  "Marcenaria",
  "Criação de Mundos",
  "Escrita",
  "Yoga",
  "Yo-YO",
  "Esportes Aéreos",
  "Arco e Flecha",
  "Astronomia",
  "Mochilão",
  "Bungle Jump",
  "Baseball",
  "Basketball",
  "Apicultura",
  "Passáros",
  "Ferraria",
  "Xadrez",
  "Bodybuilding",
  "Jiu-Jitsu",
  "Comunidade",
  "Ciclismo",
  "Radiestesia",
  "Dirigir",
  "Pescar",
  "Mergulho",
  "Voar",
  "Frisbe",
  "Forrageamento",
  "Jardinagem",
  "Caçar Fantasmas",
  "Graffiti",
  "Handball",
  "Caminhada",
  "Cavalgar",
  "Caçar",
  "Skate",
  "Caiaque",
  "Empinar Pipa",
  "Kitesurfing",
  "Detecção de Metais",
  "Corrida de Carro",
  "Mountain biking",
  "Montanhismo",
  "Caçar Cogumelos",
  "Micologia",
  "Netball",
  "Skate Nordico",
  "Orientação",
  "Paintball",
  "Parkour",
  "Fotografia",
  "Polo",
  "Rafting",
  "Rapel",
  "Escalada",
  "Andar de Patins",
  "Rugby",
  "Corrida",
  "Navegação",
  "Artes em Areia",
  "Escotismo",
  "Remo",
  "Atirar",
  "Shopping",
  "Skateboarding",
  "Esquiar",
  "Paraquedismo",
  "Slacklining",
  "Snowboarding",
  "Salto de pedra",
  "Surfar",
  "Nadar",
  "Taekwondo",
  "Tai chi",
  "Exploração Urbana",
  "Férias",
  "Restauração de Veiculos",
  "Esportes Aquáticos",
  "Damas",
  "Fofocas",
  "Artesanato",
  "Trilha Ecológicas",
  "Maquiagem",
  "Criação de Videos",
  "Criação de Música",
];

export default function VerifyHobbies(hobbie: string | undefined) {
  if (hobbie === undefined) {
    return false;
  }

  return !hobbies.includes(hobbie);
}
