const professions = [
  "Questões Socioeconômicas",
  "Ciências Atuariais",
  "Ciências Contábeis",
  "Economia",
  "Gestão de Seguros",
  "Gestão Financeira",
  "Gestão Tributária",
  "Processos Gerenciais",
  "Serviço Social",
  "Agricultura",
  "Agrimensura",
  "Agronomia",
  "Agroecologia",
  "Agronegócio",
  "Agropecuária",
  "Engenharia Agrícola",
  "Engenharia Agronômica",
  "Engenharia de Alimentos",
  "Engenharia de Pesca",
  "Medicina Veterinária",
  "Zootecnia",
  "Saúde e Bem-estar",
  "Biomedicina",
  "Enfermagem",
  "Engenharia Biomédica",
  "Estética",
  "Farmácia",
  "Fisioterapia",
  "Fonoaudiologia",
  "Gestão Hospitalar",
  "Medicina",
  "Naturologia",
  "Nutrição",
  "Odontologia",
  "Psicologia",
  "Radiologia",
  "Saúde Pública",
  "Terapia Ocupacional",
  "Educação, Diversidade e Equidade",
  "Arqueologia",
  "Astronomia",
  "Ciência e Tecnologia",
  "Ciências Biológicas",
  "Ciências Sociais",
  "Educação Artística",
  "Educação Especial",
  "Educação Física",
  "Estatística",
  "Estudante",
  "Estudos de gênero e diversidade",
  "Filosofia",
  "Física",
  "Geografia",
  "História",
  "Letras",
  "Linguística",
  "Matemática",
  "Pedagogia",
  "Pesquisador",
  "Psicopedagogia",
  "Química",
  "Recursos Naturais e Infraestrutura",
  "Bioenergia",
  "Engenharia de Energia",
  "Engenharia de Minas e Energia",
  "Engenharia de Petróleo e Gás",
  "Engenharia Nuclear",
  "Geofísica",
  "Geologia",
  "Gestão Portuária",
  "Mineração",
  "Petróleo e Gás",
  "Trabalho, Emprego e Renda",
  "Administração",
  "Arquivologia",
  "Biblioteconomia",
  "Engenharia de Segurança do Trabalho",
  "Gestão de Cooperativas",
  "Gestão de Obras",
  "Secretariado",
  "Segurança do Trabalho",
  "Indústria e Tecnologia",
  "Automação Industrial",
  "Biotecnologia",
  "Eletrônica Industrial",
  "Engenharia Aeroespacial",
  "Engenharia Aeronáutica",
  "Engenharia Acústica",
  "Engenharia da Computação",
  "Engenharia de Controle e Automação",
  "Engenharia de Inovação",
  "Engenharia de Materiais",
  "Engenharia de Operações Industriais",
  "Engenharia de Produção",
  "Engenharia de Redes de Comunicações",
  "Engenharia de Sistemas",
  "Engenharia de Telecomunicações",
  "Engenharia Elétrica",
  "Engenharia Eletrônica",
  "Engenharia em Nanotecnologia",
  "Engenharia Física",
  "Engenharia Industrial",
  "Engenharia Naval",
  "Engenharia Mecânica",
  "Engenharia Mecatrônica",
  "Engenharia Metalúrgica",
  "Manutenção de Aeronaves",
  "Engenharia Química",
  "Gestão da Produção Industrial",
  "Nanotecnologia",
  "Habitação e Questões Urbanas",
  "Arquitetura e Urbanismo",
  "Design de Interiores",
  "Engenharia Cartográfica",
  "Engenharia Civil",
  "Engenharia de Transportes",
  "Engenharia Estrutural",
  "Engenharia Sanitária",
  "Geoprocessamento",
  "Negócios Imobiliários",
  "Paisagismo",
  "Comércio e Mercado Consumidor",
  "Automobilística",
  "Comércio Exterior",
  "Engenharia Têxtil",
  "Gastronomia",
  "Gestão Comercial",
  "Gestão da Qualidade",
  "Gestão de Lazer",
  "Geografia",
  "Hotelaria",
  "Moda",
  "Museologia",
  "Piloto de Aeronaves",
  "Meio Ambiente",
  "Ecologia",
  "Engenharia Ambiental",
  "Engenharia Florestal",
  "Engenharia Hídrica",
  "Gestão Ambiental",
  "Meteorologia",
  "Oceanografia",
  "Silvicultura",
  "Direito e Justiça",
  "Carreira Militar",
  "Direito",
  "Perícia",
  "Segurança",
  "Arte e Criatividade",
  "Artes",
  "Artes Cênicas",
  "Artes Plásticas",
  "Artes Visuais",
  "Audiovisual",
  "Cinema",
  "Desempregado",
  "Dança",
  "Desenho Industrial",
  "Design",
  "Design de Games",
  "Design Gráfico",
  "Fotografia",
  "Jogador de E-Sports",
  "Música",
  "Projetos Digitais",
  "Comunicação e Sistemas de Informação",
  "Análise e Desenvolvimento de Sistemas",
  "Analista de Dados",
  "Ciência da Computação",
  "Comunicação Social",
  "Desenvolvedor",
  "Engenharia de Software",
  "Gestão da Informação",
  "Informática",
  "Jogos Digitais",
  "Jornalismo",
  "Marketing",
  "Marketing Digital",
  "Produção Multimídia",
  "Publicidade e Propaganda",
  "Rádio e TV",
  "Redes de Computadores",
  "Redes e Telecomunicações",
  "Sistemas de Informação",
  "Sistemas para Internet",
  "Tecnologia da Informação",
  "Telemática",
  "Política, Gestão e Protagonismo",
  "Gestão Desportiva",
  "Eventos",
  "Gestão Pública",
  "Logística",
  "Recursos Humanos",
  "Relações Internacionais",
  "Relações Públicas",
  "Teologia",
  "Turismo",
];
export default function VerifyProfission (profession : string | undefined) {
    if (profession === undefined) {
        return false
    }
    
    return !professions.includes(profession)
}
